version: '3.8'

services:
  postgres:
    build:
      context: .
      dockerfile: dbDockerFile  
    container_name: my-postgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro # Optional: Initialize DB with SQL file
    restart: unless-stopped

volumes:
  postgres_data:
